--- 
title: "Technical Manual" 
subtitle: "Global Soil Organic Carbon Sequestration Potential Map GSOCseq"
author: "Food and Agriculture Organization of the United Nations, Rome, 2021"
date: "23/11/2021"
#site: bookdown::bookdown_site
output: bookdown::pdf_book
header-includes:
    - \AtBeginDocument{\renewcommand{\chaptername}{Chapter}}
    - \usepackage{titling}
    - \usepackage{pdfpages}
    - \usepackage{fancyhdr}
    - \usepackage{booktabs}
    - \usepackage{longtable}
    - \usepackage{subfig}
    - \usepackage{array}
    - \usepackage{amsmath}
    - \usepackage{multirow}
    - \usepackage{wrapfig}
    - \usepackage{float}
    - \usepackage{colortbl}
    - \usepackage{pdflscape}
    - \usepackage{tabu}
    - \usepackage{threeparttable}
    - \usepackage{threeparttablex}
    - \usepackage[normalem]{ulem}
    - \usepackage{makecell}
    - \usepackage{xcolor}
    - \DeclareUnicodeCharacter{2212}{\textendash}
    - \usepackage{rotating, graphicx}
    - \usepackage{pdflscape}
    - \newcommand{\blandscape}{\begin{landscape}}
    - \newcommand{\elandscape}{\end{landscape}}
fig_caption: TRUE
documentclass: book
classoption: oneside
papersize: b5
fontsize: 10pt
bibliography: GSOCseq_references_FAO.bib
csl: food-and-agriculture-organization-of-the-united-nations.csl
nocite: '@*'
link-citations: yes
description: The GSOCseq Technical Manual
always_allow_html: yes
---



```{r set-options, echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE}
options(knitr.table.format = "latex")
library(kableExtra)
library(data.table)
library(ggplot2)
library(plotly)
library(googlesheets4)
library(tidyverse)
library(ggrepel)
library(ggtext)
library(showtext)
library(png)
library(sf)
library(waffle)
library(gridExtra)
library(patchwork)

## redefine str for the width option
str <- function(...){
  utils::str(..., strict.width = "cut")}
# reproducible results
set.seed(123)
## Boolean object for running all the code #####
# if FALSE will use precalculated RK prediction and svm tuning
#RUN.ALL <- TRUE
# Cache results
knitr::opts_chunk$set(cache=F,fig.pos = 'H',tidy.opts=list(width.cutoff=40),tidy=TRUE)


addline_format <- function(x,...){
  gsub('\\s','\n',x)
}
underscore_to_space <- function(x,...){
  gsub("_", " ",x)
}


#bookdown::render_book("index.Rmd", "bookdown::gitbook")
#bookdown::render_book("index.Rmd", "bookdown::pdf_book")
#bookdown::render_book("index.Rmd", "bookdown::word_document2")
```

\frontmatter
\addtocontents{toc}{\protect\hypersetup{hidelinks}}   
\addtocontents{lot}{\protect\hypersetup{hidelinks}}
\addtocontents{lof}{\protect\hypersetup{hidelinks}}
\tableofcontents
\listoffigures
\listoftables
\printnomenclature



# List of contributors{-}

## Authors{-}


Guillermo Peralta (GSP Secretariat)  
Luciano Di Paolo (GSP Secretariat)  
Christian Omuto (GSP Secretariat)  
Kostiantyn Viatkin (GSP Secretariat)  
Isabel Luotto (GSP Secretariat)  
Yusuf Yigini (GSP Secretariat)  


*Cover design:* Matteo Sala


## Contributers and Reviewers{-}

|               |                                      |
|-----|--------------------------------------|
| P4WG | (Pillar 4 Working Group Agency) |
| INSII | (International Network of Soil Information Institutions) |
| ITPS | (Intergovernmental Technical Panel on Soils) |
| 4per1000 SCT| (4 per 1000 Scientific and Technical Committee) |
| CIRCASA | (Coordination of International Research Cooperation on Soil Carbon Sequestration in Agriculture) |
| UNCCD-SPI | (The UNCCD Science-Policy Interface) |  
  
  
## Special Advisor {-}
Pete Smith (University of Aberdeen)

## GitHub Page {-}
Isabel Luotto (GSP Secretariat) 
  
\vfill






 



**Recommended citation:**

> FAO. 2021. GSOCseq Global Soil Organic Carbon Sequestration Potential Map
Technical Manual. G. Peralta,L. Di Paolo, C. Omuto, K. Viatkin, I. Luotto, Y. Yigini, 1st Edition, Rome. 
